
services:
  vllm:
    image: rocm/vllm:latest
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    
    group_add:
      - "video"
      - "render"
    ipc: 
      "host"
    ports: 
      - "8001:8001"
    cap_add:
      - SYS_PTRACE
    environment: 
      HIP_VISIBLE_DEVICES: 0,1
      ROCR_VISIBLE_DEVICES: 0,1

      # one of these makes it work and idk which ones
      VLLM_SKIP_P2P_CHECK: 1
      NCCL_CUMEM_ENABLE: 0
      NCCL_IB_DISABLE: 1
      HSA_ENABLE_IPC_MODE_LEGACY: 0
      # why not have all of them 

      HF_HUB_CACHE: /hf_home

    volumes:
      - /shared/huggingface:/hf_home
      - /home/amysuo12/amd2025test/vllm:/app
    command: ["/bin/sh", 
              "-c", 
              "vllm serve Salesforce/Llama-xLAM-2-70b-fc-r
              --port 8001
              --enable-auto-tool-choice
              --tool-parser-plugin ./xlam_tool_call_parser.py
              --tool-call-parser xlam
              --enforce-eager 
              --gpu-memory-utilization 0.95
              --tensor-parallel-size 2
              "]
      # --tensor-parallel-size 2
      # --max-model-len 74782
      #Salesforce/Llama-xLAM-2-70b-fc-r
              # --enable-auto-tool-choice
              # --tool-parser-plugin ./xlam_tool_call_parser.py
              # --tool-call-parser xlam
    
  open-webui:
    image: ghcr.io/open-webui/open-webui:main

    ports:
      - "3000:8080"

    restart: always

    volumes:
      - /home/amysuo12/amd2025test/open-webui:/app/backend/data
      - /home/amysuo12/amd2025test/mcp_config.json:/app/backend/data/mcp_config.json
    devices:
      - /dev/kfd
      - /dev/dri    
    environment:
      OPENAI_API_BASE_URL: http://vllm:8001/v1
      # what open webui needs to connect to vllm automatically
      ENABLE_OLLAMA_API: false
      # AUDIO_TTS_OPENAI_API_BASE_URL: http://localhost:8880/v1
      # AUDIO_TTS_OPENAI_API_KEY: "not-needed"
      # AUDIO_TTS_ENGINE: "openai"
      # AUDIO_TTS_MODEL: "kokoro"
      # AUDIO_TTS_VOICE: "af_bella"
  # kokoro-fastapi-cpu:
  #   ports:
  #       - 8880:8880
  #   image: ghcr.io/remsky/kokoro-fastapi-cpu
  #   restart: always