
services:
  vllm:
    image: 3fc3c31cc0f8
    devices:
      - /dev/kfd
      - /dev/dri
      - /dev/mem
    security_opt:
      - seccomp:unconfined
    
    group_add:
      - "video"
      - "render"
    ipc: 
      "host"
    ports: 
      - "8000:8000"

    cap_add:
      - SYS_PTRACE
    environment: 
      MODE: serve
      MODEL: "amd/Llama-3.1-8B-Instruct-FP8-KV"
      PORT: 8000
      VLLM_LOGGING_LEVEL: DEBUG
      ARGS: "--enforce-eager"

    volumes:
      - /shared/huggingface