FROM python
# Install basic development tools


WORKDIR /base-mcp
COPY base-mcp/format.py .
COPY base-mcp/server.py .
COPY base-mcp/tools.py .
COPY base-mcp/requirements.txt .
COPY base-mcp/database.xlsx .

# Install additional dependencies
RUN pip3 install -r requirements.txt



