from fastmcp import FastMCP, Context
import logging
from openai import OpenAI
logger = logging.getLogger(__name__)

def register_knowledge(mcp):
    @mcp.tool
    def get_meter():
        """Returns basic informaton about rhythm and meter in poetry for reference. Can be used in conjunction with other functions to analyze meter in retrieved or inputted poems. 
        If content of the return value is to be outputted to the user, format the output in a list of the names of meter [iamb, spondee, etc.] in order to shorten the output length and ask the user if they have a specific meterthey wish to know about."""
        meter = ("Meter is composed of two components: The number of syllables in a line and a pattern of emphasis on those syllables. A line of poetry can be broken into “feet,” which are individual units within a line of poetry. A foot of poetry has a specific number of syllables and a specific pattern of emphasis. \n"
                + "In English poetry, the most common types of metrical feet are two syllables and three syllables long. They’re characterized by their particular combination of stressed syllables (DUH or /) and unstressed syllables (duh or u). There also anceps (x) which can be either stressed or unstressed. The common stress patterns of poetic feet include: \n"
                + "Trochee (trochaic): Pronounced DUH-duh (/u), as in 'ladder': LAD-der\n"
                + "Iamb (iambic): Pronounced duh-DUH (u/), as in 'indeed': in-DEED\n"
                + "Spondee (spondaic). Pronounced DUH-DUH (//), as in 'TV.' \n"
                + "Dactyl (dactylic). Pronounced DUH-duh-duh (/uu), as in 'certainly': CER-tain-ly \n"
                + "Anapest (anapestic). Pronounced duh-duh-DUH (uu/), as in 'what the heck!' (Anapestic poetry typically divides its stressed syllables across multiple words.) \n \n"
                + "Metrical feet are repeated over the course of a line of poetry to create poetic meter. We describe the length of a poetic meter by using Greek suffixes: \n"
                + "one foot = monometer \n"
                + "two feet = dimeter \n"
                + "three feet = trimeter \n"
                + "four feet = tetrameter \n"
                + "five feet = pentameter \n"
                + "six feet = hexameter \n" 
                + "seven feet = heptameter \n"
                + "eight feet = octameter \n"
                + "eight feet = octameter \n"
                + "Combining these two components, you get many possibilities of poetic meter. Meter is typically denoted with <stress pattern> <length>, such as 'iambic pentameter' (five iambs per line for a total of 10 syllables) or dactylic hexameter. \n"
                + "Qualitative meter is characterized by stressed syllables coming at regular intervals—such as the consistent flow of five iambs in a line of a Shakespearean sonnet. \n"
                + "Quantitative meter, by contrast, is built on patterns based on syllable weight rather than stress. For instance, in quantitative meter, a line that is technically written in dactylic hexameter could contain not only dactyls (DUH-duh-duh) but also a spondee (DUH-DUH). What matters is not the 'stress' on a syllable but rather the 'length' of a syllable. \n"
                + "Accentual verse has a fixed number of stresses per line regardless of the number of syllables that are present. Accentual verse is particularly common in children's poetry; nursery rhymes and the less well-known skipping-rope rhymes are the most common form of accentual verse in the English Language. The poem, 'Baa Baa Black Sheep' has two stresses in each line but a varying number of unstressed syllables. \n"
                + "Accentual-syllabic verse is an extension of accentual verse which fixes both the number of stresses and syllables within a line or stanza.\n"
                + "Syllabic verse is a poetic form having a fixed or constrained number of syllables per line, while stress, quantity, or tone play a distinctly secondary role—or no role at all—in the verse structure. A number of English-language poets in the Modernist tradition experimented with syllabic verse. These include Marianne Moore, Dylan Thomas, Louis Zukofsky, Kenneth Rexroth and Thom Gunn. Some more traditional poets have also used syllabics, including Elizabeth Daryush and Robert Bridges. Bridges's Testament of Beauty is the longest syllabic poem in English \n"
                + "Alliterative verse is a form of verse that uses alliteration as the principal device to indicate the underlying metrical structure, as opposed to other devices such as rhyme. Old English alliterative verse comes in a variety of forms. It includes heroic poetry like Beowulf, The Battle of Brunanburh, or The Battle of Maldon; elegiac or 'wisdom' Poetry like The Ruin or The Wanderer, riddles, translations of classical and Latin poetry, saints' lives, poetic Biblical paraphrases, original Christian poems, charms, mnemonic poems used to memorize information, and the like. he use of alliterative verse continued (or was revived) in Middle English, William Langland's Piers Plowman is another important English alliterative poem. \n"
                + "Common meter in poetry: \n"
                + "Unrhymed iambic pentameter is known as blank verse, and is also heavily utilized by Shakespeare—in his dramatic works rather than his poems. John Milton’s Paradise Lost is an epic poem of blank verse and another hallmark of the form. \n"
                + " Iambic trimeter and iambic tetrameter are less common than their five-footed cousin, but they can still be found in poetry. John Keats primarily relies upon iambic tetrameter in 'La Belle Dame sans Merci,' although not every line has four feet. \n"
                + "Dactylic hexameter is sometimes called “the meter of epic” and was popular in the construction of classical Greek and Latin epic poems. Virgil's Aeneid, Ovid's Metamorphoses, and Homer's Iliad and Odyssey are all based upon dactylic hexameter. The nineteenth-century American poet Henry Wadsworth Longfellow also made ample use of dactylic hexameter, such as in his epic poem 'Evangeline.' \n"
                + "citation: 'https://www.masterclass.com/articles/poetry-101-what-is-meter-learn-the-difference-between-qualitative-and-quantitative-meter-in-poetry-with-examples',  'https://en.wikipedia.org/wiki/Metre_(poetry)'"
                + " \n")
        return meter


    @mcp.tool
    def get_rhyme():
        """Returns basic informaton about types of rhyme in poetry for reference. Can be used in conjunction with other functions to analyze meter in retrieved or inputted poems. 
        If content of the return value is to be outputted to the user, format the output in a list of the names of rhyme [perfect. eye, etc.] in order to shorten the output length and ask the user if they have a specific rhyme they wish to know about."""
        rhyme = ("The word rhyme can be used in a specific and a general sense. In the specific sense, two words rhyme if their final stressed vowel and all following sounds are identical; two lines of poetry rhyme if their final strong positions are filled with rhyming words. \n"
                + "Perfect rhymes:  a form of rhyme between two words or phrases in which The stressed vowel sound in both words must be identical, as well as any subsequent sounds. For example, the words kit and bit form a perfect rhyme, as do spaghetti and already in American accents and the onset of the stressed syllable in the words must differ. For example, pot and hot are a perfect rhyme, while leave and believe are not. Word pairs that satisfy the first condition but not the second (such as the aforementioned leave and believe) are technically identities (also known as identical rhymes or identicals). Homophones, being words of different meaning but identical pronunciation, are an example of identical rhyme. Types of perfect rhyme include: \n"
                + "single, also known as masculine: a rhyme in which the stress is on the final syllable of the words (rhyme, sublime) \n"
                + "double, also known as feminine: a rhyme in which the stress is on the penultimate (second from last) syllable of the words (picky, tricky) \n"
                + "dactylic: a rhyme in which the stress is on the antepenultimate (third from last) syllable (amorous, glamorous) \n"
                + "Feminine and dactylic rhymes may also be realized as compound (or mosaic) rhymes (poet, know it). \n"
                + " \n"
                + "General rhymes:  \n"
                + "In the general sense, general rhyme can refer to various kinds of phonetic similarity between words, and the use of such similar-sounding words in organizing verse. Rhymes in this general sense are classified according to the degree and manner of the phonetic similarity: \n"
                + "syllabic: a rhyme in which the last syllable of each word sounds the same but does not necessarily contain stressed vowels. (cleaver, silver, or pitter, patter; the final syllable of the words bottle and fiddle is /l/, a liquid consonant.) \n"
                + "imperfect (or near): a rhyme between a stressed and an unstressed syllable. (wing, caring) \n"
                + "weak (or unaccented): a rhyme between two sets of one or more unstressed syllables. (hammer, carpenter) \n"
                + "semirhyme: a rhyme with an extra syllable on one word. (bend, ending) \n"
                + "forced (or oblique): a rhyme with an imperfect match in sound. (green, fiend; one, thumb) \n"
                + "assonance: matching vowels. (shake, hate) Assonance is sometimes referred to as slant rhymes, along with consonance. \n"
                + "consonance: matching consonants. (rabies, robbers) \n"
                + "half rhyme (or slant rhyme): matching final consonants. (hand , lend) \n"
                + "pararhyme: all consonants match. (tick, tock) \n"
                + "alliteration (or head rhyme): matching initial consonants. (ship, short) \n"
                + " \n"
                + "Identical Rhymes:  If the sound preceding the stressed vowel is also identical, the rhyme is sometimes considered to be inferior and not a perfect rhyme after all. An example of such a super-rhyme or 'more than perfect rhyme' is the identical rhyme, in which not only the vowels but also the onsets of the rhyming syllables are identical, as in gun and begun. Punning rhymes, such as bare and bear are also identical rhymes. The rhyme may extend even farther back than the last stressed vowel. If it extends all the way to the beginning of the line, so that there are two lines that sound very similar or identical, it is called a holorhyme ('For I scream/For ice cream')\n"
                + "Eye Rhyme:  Eye rhymes or sight rhymes or spelling rhymes refer to similarity in spelling but not in sound where the final sounds are spelled identically but pronounced differently. Examples in English are cough, bough, and love, move. \n"
                + "Mind rhyme:  Mind rhyme is a kind of substitution rhyme similar to rhyming slang, but it is less generally codified and is 'heard' only when generated by a specific verse context. For instance, 'this sugar is neat / and tastes so sour.' If a reader or listener anticipates the word 'sweet' instead of 'sour', a mind rhyme has occurred.\n"
                + " \n"
                + "Rhymes may additionally be classified according to their position in the verse: \n"
                + "Tail rhyme (also called end rhyme or rime couée) is a rhyme in the final syllable(s) of a verse (the most common kind). \n"
                + "Internal rhyme occurs when a word or phrase in the interior of a line rhymes with a word or phrase at the end of a line, or within a different line. \n"
                + "Off-centered rhyme is a type of internal rhyme occurring in unexpected places in a given line. This is sometimes called a misplaced-rhyme scheme or a spoken word rhyme style. \n"
                + "Holorime, mentioned above, occurs when two entire lines have the same sound. \n"
                + "Echo rhyme occurs when the same syllable endings are utilized (example: disease/ease). \n"
                + "Broken rhyme is a type of enjambement producing a rhyme by dividing a word at the line break of a poem to make a rhyme with the end word of another line. \n"
                + "Cross rhyme matches a sound or sounds at the end of a line with the same sound or sounds in the middle of the following (or preceding) line. \n"
                + "Citation: 'https://en.wikipedia.org/wiki/Rhyme' \n")
        return rhyme
    
    @mcp.tool
    def get_rhyme_scheme():
        """Returns basic informaton about rhyme schemes in poetry for reference. Can be used in conjunction with other functions (in particular get_rhyme) to analyze meter in retrieved or inputted poems. 
        If content of the return value is to be outputted to the user, format the output in a list of the names of rhyme scheme [couplet, terza rima, etc.] in order to shorten the output length and ask the user if they have a specific rhyme scheme they wish to know about."""
        scheme = ("A rhyme scheme is the pattern of rhymes at the end of each line of a poem or song. It is usually referred to by using letters to indicate which lines rhyme; lines designated with the same letter all rhyme with each other. \n"
                + "Notation:  ABAB – Four-line stanza, first and third lines rhyme at the end, second and fourth lines rhyme at the end \n AB AB – Two two-line stanzas, with the first lines rhyming at the end and the second lines rhyming at the end. \n AB,AB – Single two-line stanza, with the two lines having both a single internal rhyme and a conventional rhyme at the end. \n aBaB – Two different possible meanings for a four-line stanza: First and third lines rhyme at the end, second and fourth lines are repeated verbatim or first and third lines have a feminine rhyme and the second and fourth lines have a masculine rhyme.\n A1abA2 A1abA2 – Two stanzas, where the first lines of both stanzas are exactly the same, and the last lines of both stanzas are the same. The second lines of the two stanzas are different, but rhyme at the end with the first and last lines. (In other words, all the 'A' and 'a' lines rhyme with each other, but not with the 'b' lines.)\n XAXA – Four lines, two unrhymed (X) and two with the same end rhyme (A)\n"
                + "Ballad stanza: ABCB \n  Ballade: Three stanzas of ABABBCBC followed by BCBC \n Balliol rhyme: AABB \n Boy Named Sue: AABCC(B, or infrequently D) \n Bref double: AXBC XAXC AXAB AB and other schemes, where 'X' represents unrhymed lines\n"
                + "Burns stanza: AAABAB(B) or AABCCCB\nCanopus: ABABCBC \nChant royal: Five stanzas of ababccddedE followed by either ddedE or ccddedE (capital letters represent lines repeated verbatim) \nChastushka: ABAB, ABCB, or AABB \nCinquain: ABABB \nClerihew: AABB \nCouplet: AA, but usually occurs as AA BB CC DD ... \nDécima: ABBAACCDDC \nDouble dactyl: XXXA XXXA \nEnclosed rhyme (or enclosing rhyme): ABBA \n"
                + "Englyn: complex structure \nKeatsian Ode: ABABCDECDE used in Keats' Ode on Indolence, Ode on a Grecian Urn, and Ode to a Nightingale. \nKlin: complex structure \nLimerick: AABBA \nLutherstrophe: ABABCCB or ABABCCX \nMâni: AABA \nMonorhyme: AAAAA... an identical rhyme on every line, common in Latin and Arabic \n"
                + "Octave: ABBA ABBA \nOnegin stanzas: aBaBccDDeFFeGG with the lowercase letters representing feminine rhymes and the uppercase representing masculine rhymes, written in iambic tetrameter \nOttava rima: ABABABCC \nA quatrain is any four-line stanza or poem. There are 15 possible rhyme sequences for a four-line poem; common rhyme schemes for these include AAAA, AABB, ABAB, ABBA, and ABCB. \nRhyme royal: ABABBCC \nThe Road Not Taken stanza: ABAAB as used in Robert Frost's poem The Road Not Taken, and in Glæde over Danmark by Poul Martin Møller.\n Rondeau: ABaAabAB (capital letters represent lines repeated verbatim) \nRondelet: AbAabbA (capital letters represent lines repeated verbatim) \n"
                + "Roundel: abaB bab abaB (capital letters represent lines repeated verbatim) \nRubaiyat: AABA or AAAA \n Scottish stanza: AAABAB, as used by Robert Burns in works such as 'To a Mouse'\n Sestain: AABBCC, ABABCC, AABCCB, AAABAB, and others\n Sestina: ABCDEF FAEBDC CFDABE ECBFAD DEACFB BDFECA, the seventh stanza is a tercet where line 1 has A in it but ends with D, line 2 has B in it but ends with E, line 3 has C in it but ends with F \n"
                + "Sicilian octave: ABABABAB \nSimple 4-line: ABCB \n Petrarchan sonnet: ABBA ABBA CDE CDE or ABBA ABBA CDC DCD \nShakespearean sonnet: ABAB CDCD EFEF GG \nSpenserian sonnet: ABAB BCBC CDCD EE \n Spenserian stanza: ABABBCBCC, where the last line is an alexandrine line\n Tail rhyme: B lines appear intermittently\n Terza rima: ABA BCB CDC ..., ending on YZY Z; YZY ZZ; or YZY ZYZ\n"
                + "A tristich or tercet is any three-line stanza or poem; common rhyme schemes for these are AAA (triplet) and ABA (enclosed tercet). The only other possibilities for three-line poems are AAB, ABB, and ABC. Multiple tercets can be combined into longer poems, as in the terza rima form. \n"
                + "Traditional rhyme: ABAB CDCD EFEF GHGH... \nTriolet: ABaAabAB and others (capital letters represent lines repeated verbatim) \nTriplet: AAA, often repeating such as: AAA BBB CCC DDD... \nTrova: XAXA \nVillanelle: A1bA2 abA1 abA2 abA1 abA2 abA1A2, where A1 and A2 are lines repeated exactly which rhyme with the 'a' lines \n"
                + "Citation: 'https://en.wikipedia.org/wiki/Rhyme_scheme' \n"
                + " \n"
                )
        return scheme
    
    @mcp.tool
    def get_form():
        """Returns basic informaton about forms and genres in poetry for reference. Can be used in conjunction with other functions to analyze meter in retrieved or inputted poems. 
        If content of the return value is to be outputted to the user, format the output in a list of the names of forms/genres [narrative, epic, etc.] in order to shorten the output length and ask the user if they have a specific form/genre they wish to know about. """
        form = ("In more developed, closed or 'received' poetic forms, the rhyming scheme, meter and other elements of a poem are based on sets of rules:\n"
                + "Sonnet -  Among the most common forms of poetry, popular from the Late Middle Ages on, is the sonnet, which by the 13th century had become standardized as fourteen lines following a set rhyme scheme and logical structure\n"
                + "Shi - main type of Classical Chinese poetry. Within this form of poetry the most important variations are 'folk song' styled verse (yuefu) -- a folk ballad or a poem written in the folk ballad style, and the number of lines and the length of the lines could be irregular -- with poets like Shen Yue, 'old style' verse (gushi) with poets like Li Bai, 'modern style' verse (jintishi) -- regulate the tonal variations within a poem, including the use of set patterns of the four tones of Middle Chinese -- with poets like Du Fu. In all cases, rhyming is obligatory. \n"
                + "Villanelle -  The villanelle is a nineteen-line poem made up of five triplets with a closing quatrain; the poem is characterized by having two refrains, initially used in the first and third lines of the first stanza, and then alternately used at the close of each subsequent stanza until the final quatrain, which is concluded by the two refrains. The remaining lines of the poem have an AB alternating rhyme. The villanelle has been used regularly in the English language since the late 19th century by such poets as Dylan Thomas, W. H. Auden, and Elizabeth Bishop.\n"
                + "Limerick  - A limerick is a poem that consists of five lines and is often humorous. Rhythm is very important in limericks for the first, second and fifth lines must have seven to ten syllables. However, the third and fourth lines only need five to seven. Lines 1, 2 and 5 rhyme with each other, and lines 3 and 4 rhyme with each other. Practitioners of the limerick included Edward Lear, Lord Alfred Tennyson, Rudyard Kipling, Robert Louis Stevenson\n"
                + "Haiku -  Haiku is a popular form of unrhymed Japanese poetry, Generally written in a single vertical line, the haiku contains three sections totalling 17 on (morae), structured in a ---5 pattern\n"
                + "Ode - Odes were first developed by poets writing in ancient Greek, such as Pindar, and Latin, such as Horace. Forms of odes appear in many of the cultures that were influenced by the Greeks and Latins.  The ode generally has three parts: a strophe, an antistrophe, and an epode. The strophe and the antistrophe of the ode possess similar metrical structures and, depending on the tradition, similar rhyme structures. In contrast, the epode is written with a different scheme and structure. Odes have a formal poetic diction and generally deal with a serious subject. The strophe and antistrophe look at the subject from different, often conflicting, perspectives, with the epode moving to a higher level to either view or resolve the underlying issues. Odes are often intended to be recited or sung by two choruses (or individuals), with the first reciting the strophe, the second the antistrophe, and both together the epode\n"
                + "Free Verse -   a form of poetry that does not adhere to a strict metrical structure or rhyme scheme. It allows poets to experiment with line breaks, rhythm, and imagery, creating a unique and flexible structure that often mirrors the natural rhythms of speech. While it may include rhyme or meter, these elements are not used to structure the poem as a whole. \n"
                + " \n"
                + "In addition to specific forms of poems, poetry is often thought of in terms of different genres and subgenres. A poetic genre is generally a tradition or classification of poetry based on the subject matter, style, or other broader literary characteristics \n"
                + "Types of genres: \n"
                + "Narrative poetry -  Narrative poetry is a genre of poetry that tells a story. Broadly it subsumes epic poetry, but the term 'narrative poetry' is often reserved for smaller works, generally with more appeal to human interest. Narrative poetry may be the oldest type of poetry. Notable narrative poets have included Ovid, Dante, Juan Ruiz, William Langland, Chaucer, Fernando de Rojas, Luís de Camões, Shakespeare, Alexander Pope, Robert Burns, Adam Mickiewicz, Alexander Pushkin, Letitia Elizabeth Landon, Edgar Allan Poe, Alfred Tennyson, and Anne Carson.\n"
                + "Lyric poetry - Lyric poetry is a genre that, unlike epic and dramatic poetry, does not attempt to tell a story but instead is of a more personal nature. Poems in this genre tend to be shorter, melodic, and contemplative. Rather than depicting characters and actions, it portrays the poet's own feelings, states of mind, and perceptions.  Notable poets in this genre include Christine de Pizan, John Donne, Charles Baudelaire, Gerard Manley Hopkins, Antonio Machado, and Edna St. Vincent Millay. \n"
                + "Epic Poetry -  Epic poetry is a genre of poetry, and a major form of narrative literature. This genre is often defined as lengthy poems concerning events of a heroic or important nature to the culture of the time. It recounts, in a continuous narrative, the life and works of a heroic or mythological person or group of persons. Examples of epic poems are Homer's Iliad and Odyssey, Virgil's Aeneid, the Nibelungenlied. While the composition of epic poetry, and of long poems generally, became less common in the west after the early 20th century, some notable epics have continued to be written. The Cantos by Ezra Pound, Helen in Egypt by H.D., and Paterson by William Carlos Williams are examples of modern epics.\n"
                + "Satirical Poetry -  Poetry can be a powerful vehicle for satire. The Romans had a strong tradition of satirical poetry, often written for political purposes. A notable example is the Roman poet Juvenal's satires. The same is true of the English satirical tradition. John Dryden (a Tory), the first Poet Laureate, produced in 1682 Mac Flecknoe, subtitled 'A Satire on the True Blue Protestant Poet, T.S'. (a reference to Thomas Shadwell)\n"
                + "Elegy -  An elegy is a mournful, melancholy or plaintive poem, especially a lament for the dead or a funeral song. The term 'elegy,' which originally denoted a type of poetic meter (elegiac meter - one line of poetry in dactylic hexameter followed by a line in dactylic pentameter), commonly describes a poem of mourning. An elegy may also reflect something that seems to the author to be strange or mysterious. The elegy, as a reflection on a death, on a sorrow more generally, or on something mysterious, may be classified as a form of lyric poetry. Notable practitioners of elegiac poetry have included Propertius, Jorge Manrique, Jan Kochanowski, Chidiock Tichborne, Edmund Spenser, Ben Jonson, John Milton, William Cullen Bryant, Percy Bysshe Shelley, Johann Wolfgang von Goethe, Alfred Tennyson, Walt Whitman, William Butler Yeats, Rainer Maria Rilke, and Virginia Woolf.\n"
                + "Verse fable -  The fable is an ancient literary genre, often (though not invariably) set in verse. It is a succinct story that features anthropomorphised animals, legendary creatures, plants, inanimate objects, or forces of nature that illustrate a moral lesson. Verse fables have used a variety of meter and rhyme patterns. Notable verse fabulists have included Aesop \n"
                + "Dramatic Poetry:  Dramatic poetry is drama written in verse to be spoken or sung, and appears in varying, sometimes related forms in many cultures. Greek tragedy in verse dates to the 6th century B.C., and may have been an influence on the development of Sanskrit drama, just as Indian drama in turn appears to have influenced the development of the bianwen verse dramas in China, forerunners of Chinese Opera. American poets of 20th century revive dramatic poetry, including Ezra Pound in 'Sestina: Altaforte,' T.S. Eliot with 'The Love Song of J. Alfred Prufrock'\n"
                + "Speculative Poetry:  Speculative poetry, also known as fantastic poetry (of which weird or macabre poetry is a major sub-classification), is a poetic genre which deals thematically with subjects which are 'beyond reality', whether via extrapolation as in science fiction or via weird and horrific themes as in horror fiction. Such poetry appears regularly in modern science fiction and horror fiction magazines. Edgar Allan Poe is sometimes seen as the 'father of speculative poetry'.\n"
                + "Prose poetry: Prose poetry is a hybrid genre that shows attributes of both prose and poetry. It may be indistinguishable from the micro-story. While some examples of earlier prose strike modern readers as poetic, prose poetry is commonly regarded as having originated in 19th-century France, where its practitioners included Aloysius Bertrand, Charles Baudelaire, Stéphane Mallarmé, and Arthur Rimbaud. Since the late 1980s especially, prose poetry has gained increasing popularity. \n"
                + "Light poetry: or light verse, is poetry that attempts to be humorous. Poems considered 'light' are usually brief, and can be on a frivolous or serious subject, and often feature word play, including puns, adventurous rhyme and heavy alliteration.  Notable writers of light poetry include Lewis Carroll, Ogden Nash, X. J. Kennedy, Willard R. Espy, Shel Silverstein, Gavin Ewart and Wendy Cope.\n"
                + "Slam Poetry:  Slam poetry as a genre originated in 1986 in Chicago, Illinois, when Marc Kelly Smith organized the first slam. Slam performers comment emotively, aloud before an audience, on personal, social, or other matters. Slam focuses on the aesthetics of word play, intonation, and voice inflection. \n"
                + "Citation:  'https://en.wikipedia.org/wiki/Poetry#'\n"
                + " \n"
                )
        return form
    
    @mcp.tool
    def get_device():
        """Returns basic informaton about common poetic devices (sound, meaning, rhythm) in poetry for reference. Can be used in conjunction with other functions to analyze meter in retrieved or inputted poems. 
        If content of the return value is to be outputted to the user, format the output in a list of the names of devices [alliteration, assonance, etc.] in order to shorten the output length and ask the user if they have a specific device they wish to know about. """
        device = ("Common poetic devices: "
                + "Devices pertaining to sound: \n"
                + "Alliteration - Alliteration is when two or more words start with the same consonant sound are used to emphasize an idea or action and create an emotional response. A snake, slithering slyly, for example, enhances the sense of the snake’s deviousness and danger. \n"
                + "Assonance - Whereas alliteration repeats the same consonant sounds at the start of words, assonance is repetition of vowel sounds (anywhere within the word) on the same or following lines of a poem to give a musical, internal rhyme. The sound will be a vowel sound, but doesn’t have to use a vowel, meaning you could rhyme some and mud, for example.\n"
                + "Consonance - Consonance is a similar device to alliteration and assonance in that it involves repetition of sounds. But consonance consists of repeating consonant sounds at the end (and sometimes middle) rather than beginning of words.\n"
                + "Cacophony - Cacophony involves the use of unpleasant, nasty, or harsh sounds (mainly consonants) to give the impression of chaos, disorder or dread, as in Lewis Carroll’s poem Jabberwocky: Beware the Jabberwock, my son! / The jaws that bite, the claws that catch! / Beware the Jubjub bird, and shun / The frumious Bandersnatch! \n"
                + "Euphony - On the other hand, euphony is the repetition of harmonious, musical sounds that are pleasant to read or hear. This is achieved through the use of soft consonant sounds such as m, n, w, r, f, and h and through vibrating consonants such as s, sh, and th. Known poets include Song Yue \n"
                + "Onomatopoeia - Onomatopoeia is a literary and poetic device wherein words are employed to imitate sounds associated with what they describe. Examples include smash, crack, ripple, jangling. \n"
                + "Devices pertaining to meaning: \n"
                + "Allusion - an indirect reference to a person, place, thing, history, mythology, or work of art, that the poet wants to acknowledge as relevant to the poem’s meaning. TS Eliot’s The Waste Land begins with an allusion (indeed the whole poem is packed with them), announcing 'April is the cruellest month, breeding / Lilacs out of the dead land' which alludes to and contrasts the opening of The Canterbury Tales in which the coming of April is a joyous occasion. \n"
                + "Analogy - Drawing a comparison or inference between two situations to convey the poet's message more effectively. Example: The plumbing took a maze of turns where even water got lost. \n"
                + "Conceit -  Conceit is an elaborate metaphor that runs throughout the entire poem to compare two things that do not really belong together. In contrast to simple metaphors though, a conceit will be something far more fanciful and unlikely. In To the Harbormaster by Frank O’Hara, for example, the lover is the harbormaster and the narrator a metaphysical seafarer, trying to reach his lover.\n"
                + "Irony -  Irony in poetry refers mainly to 'dramatic irony', in which the reader has important knowledge that the characters do not. The most famous example of this is in Romeo and Juliet, in which, the audience knows Juliet isn’t dead, but can’t do anything about Romeo committing suicide.\n"
                + "Metaphor - Metaphor is used in poetry to directly compare people, objects or ideas.  metaphors declare that a thing 'is' something else—he is the apple of my eye, for example—in order to to reach for a deeper understanding of the comparison.\n"
                + "Oxymoron - A combination of two words that appear to contradict each other. \n"
                + "Paradox -  As a poetic device, paradox refers to a phrase that is self-contradictory but reveals a larger truth. In Julius Caesar, for example, Shakespeare wrote that 'Cowards die many times before their deaths / The valiant never taste of death but once.'\n"
                + "Personification -  Personification is when an inanimate object, animal or idea is given human characteristics. Thus in Mirror, Silvia Plath writes from the perspective of the mirror: 'I am silver and exact. I have no preconceptions. / Whatever I see I swallow immediately.'\n"
                + "Rhetorical Question - In poetry and literature, a rhetorical question is a question that is not looking for an answer, rather is being asked to make a point. \n"
                + "Simile - The simile, like the metaphor, offers another device for comparison. However, a simile is much more blatant and uses 'like' or 'as' to draw the comparison. \n"
                + "Symbolism -  Poets use symbolism to convey hidden meanings. Places, objects, and actions can all be symbols, with many layers of meaning tied to them. Symbolism adds depth to the literal meaning of the poem.\n"
                + "Devices pertaining to rhythm: \n"
                + "Caesura - Caesura means a break or pause in the verse to allow one phrase to finish and another to begin. This can be used both to allow a natural flow to the poem, or alternatively, to add dramatic pauses, show contrast and create drama and tension. \n"
                + "Enjambment -  Enjambment is the continuation of a phrase or sentence beyond the poetic line break and sometimes beyond the couplet or stanza, without the pause that you would expect from a full stop or other punctuation. It encourages the reader to keep reading, whilst controlling the rhythm and flow of their reading.\n"
                + "Repetition -  The repetition of certain words or phrases is a method of indirectly stressing emotions or ideas and reinforcing the central point of the poem. Repetition can be used with words, phrases, lines, and even full verses. One of the most famous poems of the 20th century, Do Not Go Gentle Into That Good Night by Dylan Thomas, repeats two lines throughout the poem.\n"
                + "Citation:  'https://prowritingaid.com/poetic-devices'\n \n")
        return device